"""Generate direct-script poses from the authored Blender manifests."""
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
data=json.loads((ROOT/'assets/deployment.json').read_text())
vent=json.loads((ROOT/'assets/vent.json').read_text())
def f(v):return f'{v:.8f}f'
def vec(v):return 'new Vector3('+', '.join(f(x) for x in (-v[0],v[2],v[1]))+')'
def mul(a,b):return [[sum(x*y for x,y in zip(row,col))for col in zip(*b)]for row in a]
def transpose(a):return list(map(list,zip(*a)))
def pose(tile):
    # MWM main and subpart scenes have different axis frames; VRage uses rows.
    a=[[-1,0,0],[0,0,1],[0,1,0]];b=[[1,0,0],[0,0,1],[0,-1,0]]
    rot=transpose(mul(mul(a,tile['rotation']),transpose(b)))
    rows=[row+[0] for row in rot]+[[-tile['final'][0],tile['final'][2],tile['final'][1],1]]
    return 'new Matrix('+', '.join(f(x)for row in rows for x in row)+')'
lines=['// Generated by tools/build_animation_geometry.py from assets/deployment.json and vent.json.',
       'using VRageMath;','namespace ArcanePower {','internal static class AnimationGeometry {',
       'internal static readonly Vector3 Center = '+vec(data['center'])+';',
       'internal static readonly RingPose[] Rings = {']
for r in data['rings']:
    lines.append('new RingPose('+vec(r['axis'])+', '+f(r['tilt_degrees'])+', '+f(r['speed'])+'),')
lines+=['};','internal static readonly Vector3[] FloorSlides = {']
lines += [vec(r['slide'])+',' for r in data['leaves']]
lines+=['};','internal static readonly float[] ShieldTravel = { '+', '.join(f(s['travel_m'])for s in vent['stages'])+' };',
        'internal static readonly Vector3[] HatchSlides = { '+', '.join(vec(v) for v in vent['hatch']['slides'])+' };',
        'internal static readonly Vector3[] CeilingHatchSlides = { '+', '.join(vec(v) for v in vent['ceiling_hatch']['slides'])+' };',
        'internal const float CeilingHatchLift = '+f(vent['ceiling_hatch']['lift_m'])+';',
        'internal const float HatchDrop = '+f(vent['hatch']['drop_m'])+';',
        'internal static readonly TilePose[] Tiles = {']
for t in data['tiles']:
    lines.append('new TilePose("'+t['name']+'", '+str(t['batch'])+', '+t['model'][-1]+', '+vec(t['exit'])+', '+vec(t['staging'])+', '+pose(t)+'),')
lines+=['};','}',
        'internal struct RingPose { public Vector3 Axis; public float Tilt, Speed;',
        'public RingPose(Vector3 axis,float tilt,float speed){Axis=axis;Tilt=tilt;Speed=speed;} }',
        'internal struct TilePose { public string Name; public int Batch, Variant; public Vector3 Exit, Staging; public Matrix Final;',
        'public TilePose(string name,int batch,int variant,Vector3 exit,Vector3 staging,Matrix final){Name=name;Batch=batch;Variant=variant;Exit=exit;Staging=staging;Final=final;} }','}']
(ROOT/'src/Data/Scripts/ArcanePower/AnimationGeometry.cs').write_text('\n'.join(lines)+'\n')
print('Generated direct-script geometry: 4 rings, 4 leaves, 80 tiles, 6 shield sleeves, 4 roof and 4 ceiling doors')
